# Generated by Django 4.2.26 on 2025-12-18 07:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'text'], name='question_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
