# Generated by Django 4.2.26 on 2025-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_question_search_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_answer_per_question'),
        ),
    ]
