# Generated by Django 4.2.26 on 2026-01-07 20:20

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer_unique_correct_answer_per_question'),
    ]

    operations = [
        TrigramExtension()
    ]
