worker_processes 1;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    gzip            on;
    gzip_types      text/plain text/css application/javascript image/jpeg;

    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m;

    upstream app_server {
        server 127.0.0.1:8000;
    }

    server {
        listen 80;
        server_name localhost;

        location /static/ {
            alias /Users/artiom/Documents/VK_WEB/static/;
            expires 30d;
        }

        location ^~ /uploads/ {
            alias /Users/artiom/Documents/VK_WEB/media/;
            expires 30d;
        }

        location / {
            proxy_pass http://app_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_cache my_cache;
            proxy_cache_valid 200 10m;
            proxy_cache_valid 404 1m;
        }
    }
}
